name: 'FTP Deploy'
description: 'Automate deploying websites and more with this GitHub action'
author: 'Wind'
inputs:
    server:
      required: true
      description: 'ftp server'
    username:
      required: true
      description: 'ftp username'
    password:
      required: true
      description: 'ftp password'
    port:
      required: false
      description: 'Server port to connect to (read your web hosts docs)'
    protocol:
      required: false
      description: 'protocol to deploy with - ftp, ftps, or ftps-legacy'
    local-dir:
      required: false
      description: 'Folder to upload from, must end with trailing slash /'
    server-dir:
      required: false
      description: 'Path to upload to on the server. Must end with trailing slash /'
runs:
  using: 'composite'
  steps:
    - run: |
        ls -lah
        sudo apt-get install lftp
      shell: bash
branding:
  icon: 'upload-cloud'
  color: 'orange'