name: 'FTP Deploy Wind'
description: 'Automate deploying websites and more with this GitHub action'
author: 'Wind'
inputs:
    server:
      required: true
      description: 'FTP Server.'
    username:
      required: true
      description: 'FTP Username'
    password:
      required: true
      description: 'FTP Password'
    port:
      required: false
      description: 'Server Port'
      default: '21'
    local_dir:
      required: false
      description: 'Local directory.'
      default: './'
    server_dir:
      required: false
      description: 'Server directory'
      default: './'
    max_retries:
      description: 'Times that the lftp will be executed if an error occurred.'
      required: false
      default: '1'
    nop_interval:
      description: 'FTP - Delay in seconds between NOOP commands when downloading tail of a file.'
      required: false
      default: '2'
    ssl_allow:
      description: 'FTP - Allow SSL encryption.'
      required: false
      default: 'false'
    net_timeout:
      description: 'NET - Sets the network protocol timeout.'
      required: false
      default: '10'
    net_max_retries:
      description: 'NET - Maximum number of operation without success. 0 unlimited. 1 no retries.'
      required: false
      default: '3'
    net_persist_retries:
      description: 'NET - Ignore hard errors. When reply 5xx errors or there is too many users.'
      required: false
      default: '5'
    net_reconnect_interval_multiplier:
      description: 'sets  multiplier by which base interval is multiplied each time new attempt to perform
                    an operation fails. When the interval reaches maximum, it is reset to base value.  See
                    net:reconnect-interval-base and net:reconnect-interval-max.'
      required: false
      default: '1'
    net_reconnect_interval_base:
      description: 'sets the base minimal time between reconnects. Actual interval depends  on  net:reconвЂђ
              nect-interval-multiplier and number of attempts to perform an operation.'
      required: false
      default: '5'
    delete:
      description: 'Delete all the files inside of the remote directory.'
      required: false
      default: 'true'
    no_perms:
      description: "don't set file permissions."
      required: false
      default: 'true'
    settings:
      description: 'FTP setting config.'
      required: false
    options:
      description: 'mirror options.'
      required: false
    working-directory:
      description: 'Specifies the working directory.'
      required: false
runs:
  using: 'composite'
  steps:
    - run: $GITHUB_ACTION_PATH/init.sh
      env:
        INPUT_SERVER: ${{inputs.server}}
        INPUT_USERNAME: ${{inputs.username}}
        INPUT_PASSWORD: ${{inputs.password}}
        INPUT_PORT: ${{inputs.port}}   
        INPUT_LOCAL_DIR: ${{inputs.local_dir}}  
        INPUT_SERVER_DIR: ${{inputs.server_dir}}
        INPUT_NO_PERMS: ${{inputs.no_perms}}  
        INPUT_DELETE: ${{inputs.delete}}
        INPUT_SETTINGS: ${{inputs.settings}}
        INPUT_OPTIONS: ${{inputs.options}}
        INPUT_NOP_INTERVAL:  ${{inputs.nop_interval}}
        INPUT_SSL_ALLOW: ${{inputs.ssl_allow}}
        INPUT_MAX_RETRIES: ${{inputs.max_retries}}
        INPUT_NET_MAX_RETRIES: ${{inputs.net_max_retries}}
        INPUT_NET_TIMEOUT: ${{inputs.net_timeout}}
        INPUT_NET_PERSIST_RETRIES: ${{inputs.net_persist_retries}}
        INPUT_NET_RECONNECT_INTERVAL_MULTIPLIER: ${{inputs.net_reconnect_interval_multiplier}}
        INPUT_NET_RECONNECT_INTERVAL_BASE: ${{inputs.net_reconnect_interval_base}}
      working-directory: ${{inputs.working-directory}}
      shell: bash
branding:
  icon: 'upload-cloud'
  color: 'orange'