name: 'FTP Deploy'
description: 'Automate deploying websites and more with this GitHub action'
author: 'Wind'
inputs:
    server:
      required: true
      description: 'FTP Server.'
    username:
      required: true
      description: 'FTP Username'
    password:
      required: true
      description: 'FTP Password'
    port:
      required: false
      description: 'Server Port'
      default: '21'
    local_dir:
      required: false
      description: 'Local directory.'
      default: './'
    server_dir:
      required: false
      description: 'Server directory'
      default: './'
    max_retries:
      description: 'Times that the lftp will be executed if an error occurred.'
      required: false
      default: '1'
    ssl_allow:
      description: 'FTP - Allow SSL encryption.'
      required: false
      default: 'false'
    net_timeout:
      description: 'NET - Sets the network protocol timeout.'
      required: false
      default: '10'
    net_max_retries:
      description: 'NET - Maximum number of operation without success. 0 unlimited. 1 no retries.'
      required: false
      default: '0'
    delete:
      description: 'Delete all the files inside of the remote directory.'
      required: false
      default: 'true'
    no_perms:
      description: "don't set file permissions."
      required: false
      default: 'true'
    settings:
      description: 'FTP setting config.'
      required: false
    options:
      description: 'mirror options.'
      required: false
    working-directory:
      description: 'Specifies the working directory.'
      required: false
runs:
  using: 'composite'
  steps:
    - run: $GITHUB_ACTION_PATH/init.sh
      env:
        INPUT_SERVER: ${{inputs.server}}
        INPUT_USERNAME: ${{inputs.username}}
        INPUT_PASSWORD: ${{inputs.password}}
        INPUT_PORT: ${{inputs.port}}   
        INPUT_LOCAL_DIR: ${{inputs.local_dir}}  
        INPUT_SERVER_DIR: ${{inputs.server_dir}}
        INPUT_NO_PERMS: ${{inputs.no_perms}}  
        INPUT_DELETE: ${{inputs.delete}}
        INPUT_SETTINGS: ${{inputs.settings}}
        INPUT_OPTIONS: ${{inputs.options}}
        INPUT_SSL_ALLOW: ${{inputs.ssl_allow}}
        INPUT_MAX_RETRIES: ${{inputs.max_retries}}
        INPUT_NET_MAX_RETRIES: ${{inputs.net_max_retries}}
        INPUT_NET_TIMEOUT: ${{inputs.net_timeout}}
      working-directory: ${{inputs.working-directory}}
      shell: bash
branding:
  icon: 'upload-cloud'
  color: 'orange'