name: 'FTP Deploy'
description: 'Automate deploying websites and more with this GitHub action'
author: 'Wind'
inputs:
    server:
      required: true
      description: 'FTP Server.'
    username:
      required: true
      description: 'FTP Username'
    password:
      required: true
      description: 'FTP Password'
    port:
      required: false
      description: 'Server Port'
      default: '21'
    local-dir:
      required: false
      description: 'Local directory.'
      default: './'
    server-dir:
      required: false
      description: 'Server directory'
      default: './'
    delete:
      description: 'Delete all the files inside of the remote directory.'
      required: false
      default: 'false'
    working:
      description: 'Specifies the working directory.'
      required: false
runs:
  using: 'composite'
  steps:
    - run: |
        echo ${{ inputs.server }}        
      shell: bash
branding:
  icon: 'upload-cloud'
  color: 'orange'