name: 'FTP Deploy'
description: 'Automate deploying websites and more with this GitHub action'
author: 'Wind'
inputs:
    server:
      required: true
      description: 'FTP Server.'
    username:
      required: true
      description: 'FTP Username'
    password:
      required: true
      description: 'FTP Password'
    port:
      required: false
      description: 'Server Port'
      default: '21'
    local-dir:
      required: false
      description: 'Local directory.'
      default: './'
    server-dir:
      required: false
      description: 'Server directory'
      default: './'
    delete:
      description: 'Delete all the files inside of the remote directory.'
      required: false
      default: 'false'
    working:
      description: 'Specifies the working directory.'
      required: false
runs:
  using: 'composite'
  steps:
    - run: |
        echo "INPUT_SERVER: ${{inputs.server}}"
        echo "INPUT_USERNAME: ${{inputs.username}}"
        echo "INPUT_PASSWORD: ${{inputs.password}}"
        echo "INPUT_PORT: ${inputs.port}"
        echo "INPUT_LOCAL-DIR: ${inputs.local-dir}"
        echo "INPUT_SERVER-DIR: ${inputs.server-dir}"
        echo "INPUT_DELETE: ${inputs.delete}"
        $GITHUB_ACTION_PATH/init.sh
      shell: bash
branding:
  icon: 'upload-cloud'
  color: 'orange'